apiVersion: v1
kind: Service
metadata:
  labels:
    app: movies
  name: movies
  namespace: apps
spec:
  ports:
  - name: movies
    port: 80
    protocol: TCP
    targetPort: 5555
  selector:
    app: movies
  type: ClusterIP
