apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  namespace: apps
  labels:
    app: movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: movies
        image: adams1mon/movies:latest
        ports:
        - containerPort: 5555

