apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: location-sharing-app-cert
  namespace: apps
spec:
  dnsNames:
  # - location-sharing-app.duckdns.org
  - location-sharing-app-2.duckdns.org
  issuerRef:
    name: le-prod-http
    kind: ClusterIssuer
  secretName: location-sharing-app-tls-secret