apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-routes
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`location-sharing-app.duckdns.org`) && PathPrefix(`/api/user`)
    services:
    - kind: Service
      name: user-service
      namespace: apps
      port: 80  
  - kind: Rule
    match: Host(`location-sharing-app.duckdns.org`) && PathPrefix(`/api/groups`)
    services:
    - kind: Service
      name: group-service
      namespace: apps
      port: 80 
  - kind: Rule
    match: Host(`location-sharing-app.duckdns.org`) && PathPrefix(`/api/notifications`)
    services:
    - kind: Service
      name: notification-service
      namespace: apps
      port: 80
  - kind: Rule
    match: Host(`location-sharing-app.duckdns.org`) && PathPrefix(`/connections`)
    middlewares:
    - name: connection-gateway-strip-prefix
      namespace: apps
    services:
    - kind: Service
      name: connection-gateway
      namespace: apps
      port: 80 
  - kind: Rule
    match: Host(`location-sharing-app.duckdns.org`)
    services:
    - kind: Service
      name: frontend-service
      namespace: apps
      port: 80 