apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

- certificate.yaml
- middlewares.yaml

# might throw an error because the certificate might not be ready
- https_routes.yaml
