apiVersion: v1
kind: Secret
metadata:
  name: mongo-replicaset-secretkey-secret
  namespace: mongo
data:
  secretkey: VkpFWWVSMGFLTlJHWW9oL2RXYTFEZVdESVNLQXpVaFR3UWxia29RQ0p2NHpNNVhNdE9RMEVHYkFwdUIvYVA3Vg==
