apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: frontend-service
  namespace: apps
spec:
  ports:
  - name: frontend-http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: frontend-https
    port: 443
    protocol: TCP
    targetPort: 443

  selector:
    app: frontend-service
  type: ClusterIP
