ktor:
  development: true
  deployment:
    host: "0.0.0.0"
    port: "$PORT:8080"
  application:
    modules:
      - edu.ApplicationKt.module

kafka:
  bootstrap.servers: "$KAFKA_BOOTSTRAP_SERVERS:localhost:9092"
  max.poll.interval.ms: 5000

  # leader confirms is enough
  acks: 1

# after this prefix we generate a random value so each instance has its own consumer group
kafka_consumer_group_id_prefix: "gateway"

kafka_topics:
  session_connection_events_topic: "session.connection.events"
  session_client_message_topic: "session.client.message"
  gateway_client_message_topic: "gateway.client.message"
  group_events_topic: "gateway.group.events"

  validation_group_user_request: "validation.group.user.request"
  validation_group_user_result: "validation.group.user.result"

jwt:
  secret: "$JWT_SECRET:random-key-from-env-var"
  issuer: "location-sharing-app"
  audience: "location-sharing-app"

cors:
    originPattern: "$CORS_ORIGIN_PATTERN:http://localhost:[0-9]*"
    allowedMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
    allowedHeaders:
      - ".*"
    maxAge: 0