apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service
  namespace: apps
data:
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka-ha.kafka.svc.cluster.local:9092

  # CORS_MAPPINGS_0_URL: "/**"
  # CORS_MAPPINGS_0_ORIGIN_PATTERNS: "http://localhost:[*],https://localhost:[*],http://location-sharing-app.duckdns.org,https://location-sharing-app.duckdns.org"
  # CORS_MAPPINGS_0_ALLOWED_METHODS: "*"
  # CORS_MAPPINGS_0_ALLOWED_HEADERS: "*"
  # CORS_MAPPINGS_0_EXPOSED_HEADERS: "Authorization"
  # CORS_MAPPINGS_0_ALLOW_CREDENTIALS: "true"

  LOGGING_LEVEL_ROOT: "debug"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "debug"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA: "info"
  LOGGING_LEVEL_ORG_APACHE_KAFKA: "info"
  
