apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
  namespace: apps
spec:
  # controlled by hpa
  # replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: adams1mon/location-sharing-app_notification-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef: 
            name: notification-service
        resources:
          requests:
            cpu: 400m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: dockerhub-secret