apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: adams1mon/location-sharing-app_notification-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef: 
            name: notification-service
      imagePullSecrets:
      - name: dockerhub-secret