apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
  namespace: apps
spec:
  ports:
  - name: notification-service
    port: 80
    protocol: TCP
    targetPort: 8084
  selector:
    app: notification-service
  type: ClusterIP
