apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-gateway
  namespace: apps
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka-ha.kafka.svc.cluster.local:9092
  # CORS_ORIGIN_PATTERN: "http://localhost:[0-9]*|https://localhost:[0-9]*|http://location-sharing-app.duckdns.org|https://location-sharing-app.duckdns.org"
