apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: connection-gateway
  name: connection-gateway
  namespace: apps
spec:
  ports:
  - name: connection-gateway
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: connection-gateway
  type: ClusterIP
