version: '3'
name: redis-single-node
services:
  redis:
    image: redis:7.0
    ports:
      - 6379:6379

  redis-insight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    depends_on:
      - redis
