spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/group-service-test
    hikari:
          username: postgres
          password: changeme

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: info
    sql: info

#
#logging:
#  level:
#    root: debug
#    sql: info
#    org:
#      springframework:
#        security: debug
#        kafka: info
#      apache:
#        kafka: info

jwt:
  secret: "random-key-from-env-var"
  issuer: "location-sharing-app"
  audience: "location-sharing-app"

cors:
  mappings:
    - url: "/**"
      originPatterns: "http://localhost:[*]"
      allowedMethods: "*"
      allowedHeaders: "*"
      exposedHeaders: "Authorization"
      allowCredentials: true

server:
  port: 8083



