spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/group-service-test
    hikari:
          username: postgres
          password: changeme

#    url: jdbc:h2:mem:group-service-test
#    username: spring
#    password: pass

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    sql: debug

server:
  port: 8083



