spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service-test
    hikari:
      username: postgres
      password: changeme

  jpa:
    hibernate:
      ddl-auto: create-drop


logging:
  level:
    root: info
    sql: debug
    org.springframework.security: debug

jwt.secret: "random-key-from-env-var"

server:
  port: 8082
