spring:
  kafka:

    # common settings for all producers and consumers
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:

      # only consume the latest values
      auto-offset-reset: latest
      group-id: session-service

#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            use.type.headers: false

    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379

#logging.level:
#  org.springframework: DEBUG

topics:
  connection_events: "session.connection.events"
  client_messages:
    inbound: "session.client.message"
    outbound: "gateway.client.message"

cache:
  connection_group_ttl: PT2M
  connection_ttl: PT2M
