apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- chart.yaml

# these 2 might throw an error until the CRDs are not installed by the chart above...
- cluster_issuer_staging.yaml
- cluster_issuer_prod.yaml
