apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

- infrastructure/tools/
- infrastructure/cert-manager/
- infrastructure/traefik-ingress/

- dependencies/postgres/
- dependencies/kafka/

- apps/

