apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: frontend-service
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`location-sharing-app.duckdns.org`) || HostSNI(`localhost`)
    services:
    - name: frontend-service
      namespace: apps
      port: 443
  tls:
    passthrough: true 