apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

- connection-gateway/
- user-service/
- group-service/
- notification-service/
- frontend-service/

- ingress-routes/
