apiVersion: v1
kind: ConfigMap
metadata:
  name: group-service
  namespace: apps
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-ha.kafka.svc.cluster.local:9092
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-ha-postgresql-ha-pgpool.postgres.svc.cluster.local:5432/group_service
  SPRING_DATASOURCE_HIKARI_DDL_AUTO: update

  # CORS_MAPPINGS_0_URL: "/**"
  # CORS_MAPPINGS_0_ORIGIN_PATTERNS: "http://localhost:[*],https://localhost:[*],http://location-sharing-app.duckdns.org,https://location-sharing-app.duckdns.org"
  # CORS_MAPPINGS_0_ALLOWED_METHODS: "*"
  # CORS_MAPPINGS_0_ALLOWED_HEADERS: "*"
  # CORS_MAPPINGS_0_EXPOSED_HEADERS: "Authorization"
  # CORS_MAPPINGS_0_ALLOW_CREDENTIALS: "true"