apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: group-service
  name: group-service
  namespace: apps
spec:
  ports:
  - name: group-service
    port: 80
    protocol: TCP
    targetPort: 8083
  selector:
    app: group-service
  type: ClusterIP
