spring:
  kafka:
    # common settings for all producers and consumers
    bootstrap-servers: localhost:9092

    consumer:
      # only consume the latest values
      auto-offset-reset: latest
      group-id: session-service
#      properties:
#        spring:
#          json:
#            use.type.headers: false

  data:
    redis:
      host: localhost
      port: 6379

#logging.level:
#  org.springframework: DEBUG

topics:
  connection_events: "session.connection.events"
  client_messages:
    inbound: "session.client.message"
    outbound: "gateway.client.message"

cache:
  connection_group_ttl: PT2M
  connection_ttl: PT2M
