apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-cert
  namespace: whoami
spec:
  dnsNames:
  - location-sharing-app.duckdns.org
  # uris:
  # - https://location-sharing-app.duckdns.org
  # - wss://location-sharing-app.duckdns.org
  issuerRef:
    name: le-example-http
    kind: ClusterIssuer
  secretName: whoami-tls-secret