apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: le-prod-http
 namespace: cert-manager
spec:
 acme:
   email: location-sharing-app@gmail.com
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: cluster-issuer-le-prod-account-key
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik