apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: le-example-http
 namespace: whoami
spec:
 acme:
   email: location-sharing-app@gmail.com
   # We use the staging server here for testing to avoid hitting
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: cluster-issuer-le-account-key
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik