apiVersion: v1
kind: ConfigMap
metadata:
  name: restful-blog-config
  namespace: apps
data:
  # todo: maybe use secrets for db user & password
  # DB_USER: mongouser
  # DB_PASSWORD: mongouser
  # DB_SERVICE: mongo-statefulset-0.mongo-service.mongo.svc.cluster.local,mongo-statefulset-1.mongo-service.mongo.svc.cluster.local,mongo-statefulset-2.mongo-service.mongo.svc.cluster.local
  # DB_NAME: restful-blog
  # DB_PORT: '27017'
  # DB_CONN_OPTIONS: authSource=admin&tls=false
  # DB_CONN_STRING: "mongodb+srv://mongouser:mongouser@mongo-service.mongo.svc.cluster.local?tls=false"
  
  # TODO: why is mongodb+srv not working? (ENOTFOUND, although dns resolution succeeds)
  # TODO: auth?
  # DB_CONN_STRING: "mongodb://mongouser:mongouser@mongo-statefulset-0.mongo-service.mongo.svc.cluster.local,mongo-statefulset-1.mongo-service.mongo.svc.cluster.local,mongo-statefulset-2.mongo-service.mongo.svc.cluster.local/restful-blog"
  DB_CONN_STRING: "mongodb://mongouser:mongouser@mongo-statefulset-0.mongo-service.mongo.svc.cluster.local,mongo-statefulset-1.mongo-service.mongo.svc.cluster.local,mongo-statefulset-2.mongo-service.mongo.svc.cluster.local/restful-blog?authSource=admin"
  PORT: '5335'
  BASE_PATH: '/restful-blog'