apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: restful-blog-hpa
  namespace: apps
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restful-blog-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50