apiVersion: v1
kind: Service
metadata:
  name: restful-blog-service
  namespace: apps
  labels:
    app: restful-blog-service
spec:
  selector:
    app: restful-blog
  ports:
  - port: 80
    targetPort: 5335
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restful-blog-deployment
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restful-blog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: restful-blog
    spec:
      containers:
      - name: restful-blog
        image: adams1mon/restful-blog:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef: 
            name: restful-blog-config
        ports:
        - containerPort: 5335
          name: restful-blog
        resources:
          requests:
            cpu: 100m
      
      imagePullSecrets:
      - name: dockerhub-secret
      