apiVersion: v1
kind: Namespace
metadata:
  name: helm-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-controller
  namespace: helm-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-controller
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-controller
subjects:
  - kind: ServiceAccount
    name: helm-controller
    namespace: helm-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: helm-controller
  labels:
    app: helm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      labels:
        app: helm-controller
    spec:
      serviceAccountName: helm-controller
      containers:
        - name: helm-controller
          image: rancher/helm-controller:v0.12.1
          command: ["helm-controller"]