apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: kafka
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: kafka-cluster
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: kafka-ha.kafka.svc.cluster.local:9092
          - name: DYNAMIC_CONFIG_ENABLED
            value: 'true'
        ports:
        - containerPort: 8080
          name: kafka-ui
        resources:
          requests:
            cpu: 100m
      