apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kafka-ha
  namespace: kafka
spec:
  # https://github.com/bitnami/charts/tree/main/bitnami/kafka
  chart: oci://registry-1.docker.io/bitnamicharts/kafka
  version: 22.1.6
  targetNamespace: kafka
  valuesContent: |-
    replicaCount: 3

    service:
      ports:
        client: 9092

    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi

    serviceAccount:
      create: true
    rbac:
      create: true

    provisioning:
      enabled: true
      topics:
      - name: gateway.group.events
        partitions: 4
      - name: notifications.system
        partitions: 2
      - name: notifications.user
        partitions: 2
      - name: validation.user.request
        partitions: 2
      - name: validation.user.result
        partitions: 2
      - name: validation.group.user.request
        partitions: 2
      - name: validation.group.user.result
        partitions: 2

    kraft:
      enabled: false

    zookeeper:
      enabled: true
      replicaCount: 3
      persistence:
        enabled: true
        storageClass: local-path
        size: 250Mi
