apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-ha
  namespace: postgres
spec:
  # https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha
  chart: oci://registry-1.docker.io/bitnamicharts/postgresql-ha
  version: 11.7.6
  targetNamespace: postgres
  valuesContent: |-
    postgresql:
      username: postgres
      password: changeme

      replicaCount: 3

      initdbScripts:
        setup_user_service.sql: |
          CREATE USER user_service;
          CREATE DATABASE user_service;
          GRANT ALL PRIVILEGES ON DATABASE user_service TO user_service;
        
        setup_group_service.sql: |
          CREATE USER group_service;
          CREATE DATABASE group_service;
          GRANT ALL PRIVILEGES ON DATABASE group_service TO group_service;

    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi

    service:
      ports:
        postgresql: 5432
