postgresql:
  username: postgres
  password: changeme

  replicaCount: 1

  initdbScripts:
    setup_user_service.sql: |
      CREATE USER user_service;
      CREATE DATABASE user_service;
      GRANT ALL PRIVILEGES ON DATABASE user_service TO user_service;
    
    setup_group_service.sql: |
      CREATE USER group_service;
      CREATE DATABASE group_service;
      GRANT ALL PRIVILEGES ON DATABASE group_service TO group_service;

persistence:
  enabled: true
  storageClass: local-path
  size: 250Mi

service:
  ports:
    postgresql: 5432
