apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: apps
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-ha.kafka.svc.cluster.local:9092
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-ha-postgresql-ha-pgpool.postgres.svc.cluster.local:5432/user_service

