apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: adams1mon/location-sharing-app_user-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef: 
            name: group-service
        imagePullSecrets:
        - name: dockerhub-secret