apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: apps
spec:
  ports:
  - name: user-service
    port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: user-service
  type: ClusterIP
